"""
URL configuration for core project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.http import JsonResponse

def base_info(request):
    """Übergreifende Informationen für die API"""
    return JsonResponse({
        "message": "Coderr API",
        "version": "1.0.0",
        "status": "active"
    })

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/base-info/', base_info, name='base-info'),
    path('api/',include('auth_app.api.urls')),
    path('api/',include('profiles_app.api.urls')),
    path('api/',include('offers_app.api.urls')),
    path('api/',include('orders_app.api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
