"""
URL configuration for core project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.http import JsonResponse
from django.db.models import Avg, Count
from auth_app.models import CustomUser
from offers_app.models import Offer
from reviews_app.models import Review


def base_info(request):
    review_stats = Review.objects.aggregate(
        review_count=Count('id'),
        average_rating=Avg('rating')
    )
    
    business_profile_count = CustomUser.objects.filter(type='business').count()
    offer_count = Offer.objects.count()


    average_rating = review_stats['average_rating']
    if average_rating is not None:
        average_rating = round(average_rating, 1)
    else:
        average_rating = 0.0
    
    return JsonResponse({
        "review_count": review_stats['review_count'],
        "average_rating": average_rating,
        "business_profile_count": business_profile_count,
        "offer_count": offer_count
    })

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/base-info/', base_info, name='base-info'),
    path('api/',include('auth_app.api.urls')),
    path('api/',include('profiles_app.api.urls')),
    path('api/',include('offers_app.api.urls')),
    path('api/',include('orders_app.api.urls')),
    path('api/',include('reviews_app.api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
