# Generated by Django 5.2 on 2025-06-24 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(choices=[('customer', 'customer'), ('bussiness', 'bussines')], max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('file', models.ImageField(blank=True, upload_to='media')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('tel', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('working_hours', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(choices=[('customer', 'customer'), ('bussiness', 'bussines')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
