# Generated by Django 5.2.5 on 2025-08-25 08:37

from django.db import migrations, models
import django.db.models.deletion


def migrate_reviews_to_offers(apps, schema_editor):
    Review = apps.get_model('reviews_app', 'Review')
    Offer = apps.get_model('offers_app', 'Offer')
    
    # Für jede Bewertung, nehmen wir das erste Angebot des Business Users
    for review in Review.objects.all():
        try:
            # Finde das erste Angebot des Business Users
            offer = Offer.objects.filter(user=review.business_user).first()
            if offer:
                review.offer = offer
                review.save()
            else:
                # Wenn kein Angebot gefunden wird, lösche die Bewertung
                review.delete()
        except Exception:
            # Bei Fehlern lösche die Bewertung
            review.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0001_initial'),
        ('offers_app', '0001_initial'),
    ]

    operations = [
        # Füge das neue offer Feld hinzu
        migrations.AddField(
            model_name='review',
            name='offer',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reviews',
                to='offers_app.offer'
            ),
        ),
        
        # Migriere die Daten
        migrations.RunPython(migrate_reviews_to_offers),
        
        # Mache das Feld nicht-nullable
        migrations.AlterField(
            model_name='review',
            name='offer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reviews',
                to='offers_app.offer'
            ),
        ),
        
        # Ändere unique_together
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('offer', 'reviewer')},
        ),
        
        # Entferne das alte business_user Feld
        migrations.RemoveField(
            model_name='review',
            name='business_user',
        ),
    ]
